name: Artifact

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
  workflow_dispatch:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG_LATEST: artifact

jobs:
  package:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - id: meta
        run: | 
          s="${{ github.sha }}"; rev="${s:0:7}"; x="${{ github.ref_name }}"; 
          echo "tag=${x/main/${rev}}" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          tags: | 
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.TAG_LATEST }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}
          outputs: type=docker,dest=${{ runner.temp }}/${{ env.TAG_LATEST }}-amd64.tar
          provenance: false
          push: ${{ github.ref_name != 'main' }} # if tagged
      - name: 🌬️ Push it to Zenodo
        run: |
          curl -H 'Authorization: Bearer ${{ secrets.ZENODO_TOKEN }}' \
          --upload-file ${{ runner.temp }}/${{ env.TAG_LATEST }}-amd64.tar \
          https://zenodo.org/api/files/${{ secrets.ZENODO_BUCKET }}/${{ env.TAG_LATEST }}-amd64.tar
