name: Docker

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:
    branches: [ main ]

jobs:
  container:
    name: Docker build test
    runs-on: ubuntu-latest
    steps:
      - uses: pierreraffa/cancel-previous-runs-action@1.11
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true